export default {
    OPERATOR: "OPERATOR",
    ENTERPRISE_ADMIN: "ENTERPRISE_ADMIN",
    SUPER_ADMIN: "SUPER_ADMIN",
    CPO_ADMIN: "CPO_ADMIN",
    FIELD_OPERATOR: "FIELD_OPERATOR",
    CORPORATE_ADMIN: "CORPORATE_ADMIN",
};